#!/usr/bin/env bash
# 01 Repository Intelligence · 客户仓事实摸底（只记录可观察事实，不替人做业务判断）
# Usage: ./scripts/onboard-repo.sh /path/to/customer-repo
set -euo pipefail

ROOT="${1:-}"
if [[ -z "$ROOT" || ! -d "$ROOT" ]]; then
  echo "Usage: $0 /path/to/customer-repo" >&2
  exit 1
fi

ROOT="$(cd "$ROOT" && pwd)"
AI4SE="$ROOT/.ai4se"
STORY="$ROOT/.story"

echo "Onboarding Repository Intelligence slots under: $ROOT"

mkdir -p \
  "$AI4SE/repository" \
  "$AI4SE/knowledge" \
  "$AI4SE/learning" \
  "$AI4SE/rules" \
  "$AI4SE/skills" \
  "$AI4SE/index" \
  "$STORY"

# Minimal index stubs (empty knowledge allowed; structure required)
if [[ ! -f "$AI4SE/index/knowledge.yaml" ]]; then
  cat > "$AI4SE/index/knowledge.yaml" <<'EOF'
# id -> path / kind / tags / refs  (Lifecycle maintains; Builder retrieves)
entries: []
EOF
fi

# Per-role model selection (optional; Claude/Cursor --model)
mkdir -p "$AI4SE/runtime"
if [[ ! -f "$AI4SE/runtime/role-models.yaml" ]]; then
  cat > "$AI4SE/runtime/role-models.yaml" <<'EOF'
# Per-role CLI model (omit --model when blank → vendor default)
# Override with AI4SE_MODEL_* or Field --model-analysis / --model-development / ...
# default: claude-sonnet-4-5
# roles:
#   analysis: claude-sonnet-4-5
#   planning: claude-sonnet-4-5
#   development: deepseek-v4-pro
#   review: claude-sonnet-4-5
#   acceptance: <acceptance-model>
default:
roles: {}
EOF
fi

write_maven_baseline() {
  local pom="$ROOT/pom.xml"
  local out="$AI4SE/repository/baseline.md"
  local modules
  modules="$(grep -E '^\s*<module>[^<]+</module>' "$pom" 2>/dev/null | sed -E 's/.*<module>([^<]+)<\/module>.*/\1/' || true)"
  local java_ver
  java_ver="$(grep -E '<java.version>' "$pom" 2>/dev/null | head -1 | sed -E 's/.*<java.version>([^<]+)<\/java.version>.*/\1/' || true)"
  local artifact=""
  # Prefer project artifactId after </parent> (skip spring-boot parent id). Else first artifactId.
  if grep -q '</parent>' "$pom" 2>/dev/null; then
    artifact="$(sed -n '/<\/parent>/,$p' "$pom" | grep -E '<artifactId>' | head -1 \
      | sed -E 's/.*<artifactId>([^<]+)<\/artifactId>.*/\1/' || true)"
  fi
  if [[ -z "$artifact" ]]; then
    # No parent block (or empty): take first artifactId under project (usually correct).
    artifact="$(grep -E '<artifactId>' "$pom" 2>/dev/null | head -1 \
      | sed -E 's/.*<artifactId>([^<]+)<\/artifactId>.*/\1/' || true)"
  fi
  # Guard: never record known parent BOM ids as project id
  if [[ "$artifact" == "spring-boot-starter-parent" || "$artifact" == "spring-boot-dependencies" ]]; then
    artifact="$(grep -E '<artifactId>' "$pom" 2>/dev/null | grep -v starter-parent | grep -v spring-boot-dependencies | head -1 \
      | sed -E 's/.*<artifactId>([^<]+)<\/artifactId>.*/\1/' || true)"
  fi

  {
    echo "# Repository Baseline (Facts / Map — no AI analysis)"
    echo
    echo "> Generated by onboard-repo.sh from observable files. Edit to correct; do not add change suggestions."
    echo
    echo "## Identity"
    echo "- root: \`$ROOT\`"
    if [[ -n "$artifact" ]]; then
      echo "- root artifactId: \`$artifact\`"
    fi
    if [[ -n "$java_ver" ]]; then
      echo "- java.version (from pom): \`$java_ver\`"
    fi
    echo "- build system: Maven (pom.xml present)"
    echo
    echo "## Modules"
    if [[ -n "$modules" ]]; then
      while IFS= read -r m; do
        [[ -z "$m" ]] && continue
        echo "- \`$m\`"
      done <<< "$modules"
    else
      echo "- (no \`<module>\` entries parsed from root pom.xml)"
    fi
    echo
    echo "## Build entry"
    echo "- see \`.ai4se/repository/entries.yaml\`"
    echo "- default probe: \`mvn -q -DskipTests package\`"
    echo
    echo "## Test entry"
    echo "- repository-wide test command: not inferred; see \`.ai4se/repository/verification-capabilities.yaml\`"
    echo "- delivery verification is defined per Story by frozen acceptance probes and any explicitly configured quality gates"
    echo
    echo "## Risk surface"
    echo "- Existing historical tests may require services (DB/Redis) and are inventory assets, not an automatic onboarding gate"
    echo
    echo "## Architecture notes"
    echo "- Facts derived from root pom.xml module list and properties only"
    echo
    echo "## Digitization status"
    echo "| Slot | Status |"
    echo "|------|--------|"
    echo "| entries.yaml | probed or unknown |"
    echo "| baseline.md | maven probe (this file) |"
    echo "| knowledge/learning/rules/skills | structure only until Lifecycle |"
  } > "$out"
}

if [[ ! -f "$AI4SE/repository/baseline.md" ]]; then
  if [[ -f "$ROOT/pom.xml" ]]; then
    write_maven_baseline
  elif [[ -f "$ROOT/package.json" ]]; then
    cat > "$AI4SE/repository/baseline.md" <<EOF
# Repository Baseline (Facts / Map — no AI analysis)

> Generated by onboard-repo.sh. Edit to correct; do not add change suggestions.

## Identity
- root: \`$ROOT\`
- build system: npm/Node (package.json present)

## Modules
- (not parsed from package.json workspaces in this probe)

## Build entry
- see \`.ai4se/repository/entries.yaml\`
- default probe: \`npm run build\`

## Test entry
- repository-wide test command: not inferred; see \`.ai4se/repository/verification-capabilities.yaml\`
- delivery verification is defined per Story by frozen acceptance probes and any explicitly configured quality gates

## Risk surface
- Existing scripts are inventory assets; do not make an unrelated historical test a Story gate

## Architecture notes
- Facts from file presence only

## Digitization status
| Slot | Status |
|------|--------|
| entries.yaml | probed |
| baseline.md | npm probe (this file) |
| knowledge/learning/rules/skills | structure only until Lifecycle |
EOF
  elif [[ -f "$ROOT/build.gradle" || -f "$ROOT/build.gradle.kts" ]]; then
    cat > "$AI4SE/repository/baseline.md" <<EOF
# Repository Baseline (Facts / Map — no AI analysis)

> Generated by onboard-repo.sh. Edit to correct; do not add change suggestions.

## Identity
- root: \`$ROOT\`
- build system: Gradle (build.gradle present)

## Modules
- (multi-project includes not parsed in this probe)

## Build entry
- see \`.ai4se/repository/entries.yaml\`
- default probe: \`./gradlew assemble\`

## Test entry
- repository-wide test command: not inferred; see \`.ai4se/repository/verification-capabilities.yaml\`
- delivery verification is defined per Story by frozen acceptance probes and any explicitly configured quality gates

## Risk surface
- Existing Gradle tests are inventory assets; execute only target-relevant validation

## Architecture notes
- Facts from file presence only

## Digitization status
| Slot | Status |
|------|--------|
| entries.yaml | probed |
| baseline.md | gradle probe (this file) |
| knowledge/learning/rules/skills | structure only until Lifecycle |
EOF
  else
    cat > "$AI4SE/repository/baseline.md" <<EOF
# Repository Baseline (Facts / Map — no AI analysis)

> Generated by onboard-repo.sh. Edit to correct; do not add change suggestions.

## Identity
- root: \`$ROOT\`
- build system: unknown (no pom.xml / package.json / build.gradle detected)

## Modules
- none detected at onboard time

## Build entry
- see \`.ai4se/repository/entries.yaml\` (\`unknown\`)

## Test entry
- see \`.ai4se/repository/entries.yaml\` (\`unknown\`)

## Risk surface
- No build tool detected — pathway Verify cannot run customer tests until entries are set honestly

## Architecture notes
- Empty probe only

## Digitization status
| Slot | Status |
|------|--------|
| entries.yaml | unknown |
| baseline.md | empty-repo probe (this file) |
| knowledge/learning/rules/skills | structure only until Lifecycle |
EOF
  fi
elif grep -q '(fill)' "$AI4SE/repository/baseline.md" 2>/dev/null; then
  echo "WARN: baseline.md still contains (fill) — pathway will refuse until Facts are digitized." >&2
fi

if [[ ! -f "$AI4SE/repository/entries.yaml" ]]; then
  {
    echo "# Auto-detected build entry pointers."
    echo "# Repository-wide tests remain unknown until a Story establishes a target-relevant probe."
    build_lines=()
    detect_dir() {
      local dir="$1"
      local prefix="$2"
      if [[ -f "$dir/pom.xml" ]]; then
        build_lines+=("  - ${prefix}mvn -q -DskipTests package")
      fi
      if [[ -f "$dir/package.json" ]]; then
        if grep -Eq '"build"[[:space:]]*:' "$dir/package.json" 2>/dev/null; then
          build_lines+=("  - ${prefix}npm run build")
        fi
      fi
      if [[ -f "$dir/build.gradle" || -f "$dir/build.gradle.kts" ]]; then
        build_lines+=("  - ${prefix}./gradlew assemble")
      fi
    }
    detect_dir "$ROOT" ""
    for sub in "$ROOT"/*/; do
      [[ -d "$sub" ]] || continue
      sub="${sub%/}"
      base="$(basename "$sub")"
      case "$base" in
        target|node_modules|.git|.idea|build|dist|out) continue ;;
      esac
      detect_dir "$sub" "cd ${base} && "
    done
    if [[ ${#build_lines[@]} -eq 0 ]]; then
      echo "build: unknown"
      echo "test: unknown"
    else
      echo "build:"
      printf '%s\n' "${build_lines[@]}"
      echo "test: unknown"
    fi
  } > "$AI4SE/repository/entries.yaml"
fi

# A customer can only judge an onboarding result if the structural facts are
# visible and cite their source.  These documents deliberately keep unknowns
# visible: neither this shell probe nor a later model call is allowed to turn a
# guessed architecture/business rule into an established repository fact.
write_repository_facts() {
  local out="$AI4SE/repository/facts.md"
  local git_head=""
  local git_branch=""
  local java_count=0
  local test_count=0
  local controller_count=0
  local source_refs=()

  # A linked Git worktree has a .git *file* that points at the common Git dir.
  # Ask Git instead of checking for a directory so facts are equally traceable
  # in the customer main checkout and the isolated Story worktree.
  if git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git_head="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || true)"
    git_branch="$(git -C "$ROOT" branch --show-current 2>/dev/null || true)"
    source_refs+=("- git metadata: \`.git/\`")
  fi
  if [[ -f "$ROOT/pom.xml" ]]; then source_refs+=("- Maven descriptor: \`pom.xml\`"); fi
  if [[ -f "$ROOT/package.json" ]]; then source_refs+=("- Node descriptor: \`package.json\`"); fi
  if [[ -f "$ROOT/build.gradle" || -f "$ROOT/build.gradle.kts" ]]; then source_refs+=("- Gradle descriptor: \`build.gradle*\`"); fi
  java_count="$(find "$ROOT" -path "$ROOT/.git" -prune -o -path '*/target' -prune -o -name '*.java' -type f -print 2>/dev/null | wc -l | tr -d ' ')"
  test_count="$(find "$ROOT" -path "$ROOT/.git" -prune -o -path '*/target' -prune -o \( -name '*Test.java' -o -name '*Tests.java' \) -type f -print 2>/dev/null | wc -l | tr -d ' ')"
  controller_count="$(find "$ROOT" -path "$ROOT/.git" -prune -o -path '*/target' -prune -o \( -name '*Controller.java' -o -name '*Resource.java' \) -type f -print 2>/dev/null | wc -l | tr -d ' ')"

  {
    echo "# Repository Facts"
    echo
    echo "> Generated by \`onboard-repo.sh\` from filesystem and Git metadata; this is an evidence index, not an architecture recommendation."
    echo
    echo "## Snapshot"
    echo "- workspace: \`$ROOT\`"
    if [[ -n "$git_head" ]]; then echo "- git_head: \`$git_head\`"; fi
    if [[ -n "$git_branch" ]]; then echo "- git_branch: \`$git_branch\`"; fi
    echo "- observed_at_utc: \`$(date -u +%Y-%m-%dT%H:%M:%SZ)\`"
    echo
    echo "## Observable inventory"
    echo "- Java source files: $java_count"
    echo "- Java test-named files: $test_count"
    echo "- Controller/Resource-named files: $controller_count"
    echo "- build entry declarations: \`.ai4se/repository/entries.yaml\` (not executed by onboard)"
    echo "- verification capability inventory: \`.ai4se/repository/verification-capabilities.yaml\` (not executed by onboard)"
    echo
    echo "## Sources"
    if [[ ${#source_refs[@]} -eq 0 ]]; then echo "- No recognised build descriptor found"; else printf '%s\n' "${source_refs[@]}"; fi
    echo
    echo "## Unknowns requiring confirmation"
    echo "- Which declared build/test entry is valid in this environment."
    echo "- Runtime dependencies, credentials and external services."
    echo "- Business ownership, domain meanings and release policy."
  } > "$out"
}

write_module_map() {
  local out="$AI4SE/repository/module-map.md"
  {
    echo "# Module Map (Observed)"
    echo
    echo "> This map lists structural locations only. A path is not evidence of responsibility or business semantics."
    echo
    echo "## Root build descriptors"
    for file in pom.xml package.json build.gradle build.gradle.kts settings.gradle settings.gradle.kts; do
      if [[ -f "$ROOT/$file" ]]; then echo "- \`$file\`"; fi
    done
    echo
    echo "## Maven modules declared by root pom"
    local modules
    modules="$(grep -E '^\s*<module>[^<]+</module>' "$ROOT/pom.xml" 2>/dev/null | sed -E 's/.*<module>([^<]+)<\/module>.*/\1/' || true)"
    if [[ -n "$modules" ]]; then
      while IFS= read -r m; do [[ -n "$m" ]] && echo "- \`$m\` (source: \`pom.xml\`)"; done <<< "$modules"
    else
      echo "- none observed or root pom.xml absent"
    fi
    echo
    echo "## Source roots (depth <= 4)"
    local found=0
    while IFS= read -r root_path; do
      [[ -z "$root_path" ]] && continue
      echo "- \`${root_path#$ROOT/}\`"
      found=1
    done < <(find "$ROOT" -path "$ROOT/.git" -prune -o -path '*/target' -prune -o -type d \( -path '*/src/main' -o -path '*/src/test' -o -path '*/src/main/java' -o -path '*/src/test/java' -o -path '*/src/main/resources' -o -path '*/src/test/resources' \) -print 2>/dev/null | sort)
    if [[ "$found" -eq 0 ]]; then echo "- none observed"; fi
    echo
    echo "## Unknowns"
    echo "- Dependency direction and module ownership are not inferred by the filesystem probe."
    echo "- API/data boundaries must be established by Story analysis with source references."
  } > "$out"
}

write_verification_capabilities() {
  local out="$AI4SE/repository/verification-capabilities.yaml"
  local java_tests node_projects maven_skip
  java_tests="$(find "$ROOT" -path "$ROOT/.git" -prune -o -path '*/target' -prune -o \( -name '*Test.java' -o -name '*Tests.java' \) -type f -print 2>/dev/null | wc -l | tr -d ' ')"
  node_projects="$(find "$ROOT" -path "$ROOT/.git" -prune -o -path '*/node_modules' -prune -o -name package.json -type f -print 2>/dev/null | wc -l | tr -d ' ')"
  # grep returns 1 when no descriptor contains this property.  Under pipefail that is an
  # expected observation, not an onboarding failure.
  maven_skip="$( (grep -R -E -l '<maven\.test\.skip>[[:space:]]*true' "$ROOT" --include='pom.xml' 2>/dev/null || true) | wc -l | tr -d ' ')"
  {
    echo "# Verification Capability Map"
    echo "# Generated from repository descriptors and file names. No test command is run here."
    echo "baseline_status: inventory_only"
    echo "java_test_named_files: $java_tests"
    echo "node_package_json_files: $node_projects"
    echo "maven_descriptors_with_test_skip_true: $maven_skip"
    echo "repository_wide_test_entry: not_configured"
    echo "story_delivery_rule: frozen_acceptance_probes_required"
    echo "notes:"
    echo "  - Existing test classes and package scripts are assets to inspect, not evidence that they run locally."
    echo "  - External services are considered only if a target Story touches them."
    echo "  - API, DB, UI and messaging Stories must freeze at least one probe across the changed boundary."
    echo "observed_node_scripts:"
    while IFS= read -r package; do
      [[ -z "$package" ]] && continue
      local rel
      rel="${package#$ROOT/}"
      echo "  - path: $rel"
      if grep -Eq '"test"[[:space:]]*:' "$package" 2>/dev/null; then
        echo "    test_script: declared"
      else
        echo "    test_script: not_configured"
      fi
    done < <(find "$ROOT" -path "$ROOT/.git" -prune -o -path '*/node_modules' -prune -o -name package.json -type f -print 2>/dev/null | sort)
  } > "$out"
}

write_onboard_report() {
  local out="$AI4SE/repository/onboard-report.md"
  {
    echo "# Onboard Report"
    echo
    echo "- status: FACTS_CAPTURED_NOT_EXECUTION_VERIFIED"
    echo "- facts: \`.ai4se/repository/facts.md\`"
    echo "- module_map: \`.ai4se/repository/module-map.md\`"
    echo "- baseline: \`.ai4se/repository/baseline.md\`"
    echo "- entries: \`.ai4se/repository/entries.yaml\`"
    echo "- verification_capabilities: \`.ai4se/repository/verification-capabilities.yaml\`"
    echo
    echo "## Next automatic action"
    echo
    echo "1. Run bounded semantic Discovery using the observable facts."
    echo "2. Promote source-cited Discovery output as working knowledge; business Unknowns remain unresolved."
    echo "3. Start a Story; its frozen acceptance probes establish the delivery verification boundary."
    echo
    echo "No command was executed by onboarding, and no business knowledge was asserted."
  } > "$out"
}

# Refresh fact documents: they are a snapshot, unlike operator-owned entries.
write_repository_facts
write_module_map
write_verification_capabilities
write_onboard_report

for f in rules/.gitkeep skills/.gitkeep knowledge/.gitkeep learning/.gitkeep; do
  mkdir -p "$(dirname "$AI4SE/$f")"
  touch "$AI4SE/$f"
done

if [[ ! -f "$STORY/README.md" ]]; then
  cat > "$STORY/README.md" <<'EOF'
# .story/

Per-story process artifacts live under `.story/<story-id>/`.
Managed by Delivery Orchestration; not business knowledge.
EOF
fi

echo "Done. Facts captured at .ai4se/repository/facts.md, module-map.md and verification-capabilities.yaml."
echo "Next: bounded semantic Discovery; no repository-wide test claim was made."
