#!/usr/bin/env bash
# 01 Repository Intelligence · 客户仓建槽（数字化槽位，不思考）
# Usage: ./scripts/onboard-repo.sh /path/to/customer-repo
set -euo pipefail

ROOT="${1:-}"
if [[ -z "$ROOT" || ! -d "$ROOT" ]]; then
  echo "Usage: $0 /path/to/customer-repo" >&2
  exit 1
fi

ROOT="$(cd "$ROOT" && pwd)"
AI4SE="$ROOT/.ai4se"
STORY="$ROOT/.story"

echo "Onboarding Repository Intelligence slots under: $ROOT"

mkdir -p \
  "$AI4SE/repository" \
  "$AI4SE/knowledge" \
  "$AI4SE/learning" \
  "$AI4SE/rules" \
  "$AI4SE/skills" \
  "$AI4SE/index" \
  "$STORY"

# Minimal index stubs (empty knowledge allowed; structure required)
if [[ ! -f "$AI4SE/index/knowledge.yaml" ]]; then
  cat > "$AI4SE/index/knowledge.yaml" <<'EOF'
# id -> path / kind / tags / refs  (Lifecycle maintains; Builder retrieves)
entries: []
EOF
fi

write_maven_baseline() {
  local pom="$ROOT/pom.xml"
  local out="$AI4SE/repository/baseline.md"
  local modules
  modules="$(grep -E '^\s*<module>[^<]+</module>' "$pom" 2>/dev/null | sed -E 's/.*<module>([^<]+)<\/module>.*/\1/' || true)"
  local java_ver
  java_ver="$(grep -E '<java.version>' "$pom" 2>/dev/null | head -1 | sed -E 's/.*<java.version>([^<]+)<\/java.version>.*/\1/' || true)"
  local artifact=""
  # Prefer project artifactId after </parent> (skip spring-boot parent id). Else first artifactId.
  if grep -q '</parent>' "$pom" 2>/dev/null; then
    artifact="$(sed -n '/<\/parent>/,$p' "$pom" | grep -E '<artifactId>' | head -1 \
      | sed -E 's/.*<artifactId>([^<]+)<\/artifactId>.*/\1/' || true)"
  fi
  if [[ -z "$artifact" ]]; then
    # No parent block (or empty): take first artifactId under project (usually correct).
    artifact="$(grep -E '<artifactId>' "$pom" 2>/dev/null | head -1 \
      | sed -E 's/.*<artifactId>([^<]+)<\/artifactId>.*/\1/' || true)"
  fi
  # Guard: never record known parent BOM ids as project id
  if [[ "$artifact" == "spring-boot-starter-parent" || "$artifact" == "spring-boot-dependencies" ]]; then
    artifact="$(grep -E '<artifactId>' "$pom" 2>/dev/null | grep -v starter-parent | grep -v spring-boot-dependencies | head -1 \
      | sed -E 's/.*<artifactId>([^<]+)<\/artifactId>.*/\1/' || true)"
  fi

  {
    echo "# Repository Baseline (Facts / Map — no AI analysis)"
    echo
    echo "> Generated by onboard-repo.sh from observable files. Edit to correct; do not add change suggestions."
    echo
    echo "## Identity"
    echo "- root: \`$ROOT\`"
    if [[ -n "$artifact" ]]; then
      echo "- root artifactId: \`$artifact\`"
    fi
    if [[ -n "$java_ver" ]]; then
      echo "- java.version (from pom): \`$java_ver\`"
    fi
    echo "- build system: Maven (pom.xml present)"
    echo
    echo "## Modules"
    if [[ -n "$modules" ]]; then
      while IFS= read -r m; do
        [[ -z "$m" ]] && continue
        echo "- \`$m\`"
      done <<< "$modules"
    else
      echo "- (no \`<module>\` entries parsed from root pom.xml)"
    fi
    echo
    echo "## Build entry"
    echo "- see \`.ai4se/repository/entries.yaml\`"
    echo "- default probe: \`mvn -q -DskipTests package\`"
    echo
    echo "## Test entry"
    echo "- see \`.ai4se/repository/entries.yaml\`"
    echo "- default probe: \`mvn -q test\` (may be heavy / env-sensitive on large reactors — narrow before pathway)"
    echo
    echo "## Risk surface"
    echo "- Multi-module reactors: root \`mvn test\` may require services (DB/Redis) — verify entries honesty before pathway"
    echo
    echo "## Architecture notes"
    echo "- Facts derived from root pom.xml module list and properties only"
    echo
    echo "## Digitization status"
    echo "| Slot | Status |"
    echo "|------|--------|"
    echo "| entries.yaml | probed or unknown |"
    echo "| baseline.md | maven probe (this file) |"
    echo "| knowledge/learning/rules/skills | structure only until Lifecycle |"
  } > "$out"
}

if [[ ! -f "$AI4SE/repository/baseline.md" ]]; then
  if [[ -f "$ROOT/pom.xml" ]]; then
    write_maven_baseline
  elif [[ -f "$ROOT/package.json" ]]; then
    cat > "$AI4SE/repository/baseline.md" <<EOF
# Repository Baseline (Facts / Map — no AI analysis)

> Generated by onboard-repo.sh. Edit to correct; do not add change suggestions.

## Identity
- root: \`$ROOT\`
- build system: npm/Node (package.json present)

## Modules
- (not parsed from package.json workspaces in this probe)

## Build entry
- see \`.ai4se/repository/entries.yaml\`
- default probe: \`npm run build\`

## Test entry
- see \`.ai4se/repository/entries.yaml\`
- default probe: \`npm test\`

## Risk surface
- Confirm scripts exist in package.json before pathway

## Architecture notes
- Facts from file presence only

## Digitization status
| Slot | Status |
|------|--------|
| entries.yaml | probed |
| baseline.md | npm probe (this file) |
| knowledge/learning/rules/skills | structure only until Lifecycle |
EOF
  elif [[ -f "$ROOT/build.gradle" || -f "$ROOT/build.gradle.kts" ]]; then
    cat > "$AI4SE/repository/baseline.md" <<EOF
# Repository Baseline (Facts / Map — no AI analysis)

> Generated by onboard-repo.sh. Edit to correct; do not add change suggestions.

## Identity
- root: \`$ROOT\`
- build system: Gradle (build.gradle present)

## Modules
- (multi-project includes not parsed in this probe)

## Build entry
- see \`.ai4se/repository/entries.yaml\`
- default probe: \`./gradlew assemble\`

## Test entry
- see \`.ai4se/repository/entries.yaml\`
- default probe: \`./gradlew test\`

## Risk surface
- Confirm Gradle wrapper / JDK before pathway

## Architecture notes
- Facts from file presence only

## Digitization status
| Slot | Status |
|------|--------|
| entries.yaml | probed |
| baseline.md | gradle probe (this file) |
| knowledge/learning/rules/skills | structure only until Lifecycle |
EOF
  else
    cat > "$AI4SE/repository/baseline.md" <<EOF
# Repository Baseline (Facts / Map — no AI analysis)

> Generated by onboard-repo.sh. Edit to correct; do not add change suggestions.

## Identity
- root: \`$ROOT\`
- build system: unknown (no pom.xml / package.json / build.gradle detected)

## Modules
- none detected at onboard time

## Build entry
- see \`.ai4se/repository/entries.yaml\` (\`unknown\`)

## Test entry
- see \`.ai4se/repository/entries.yaml\` (\`unknown\`)

## Risk surface
- No build tool detected — pathway Verify cannot run customer tests until entries are set honestly

## Architecture notes
- Empty probe only

## Digitization status
| Slot | Status |
|------|--------|
| entries.yaml | unknown |
| baseline.md | empty-repo probe (this file) |
| knowledge/learning/rules/skills | structure only until Lifecycle |
EOF
  fi
elif grep -q '(fill)' "$AI4SE/repository/baseline.md" 2>/dev/null; then
  echo "WARN: baseline.md still contains (fill) — pathway will refuse until Facts are digitized." >&2
fi

if [[ ! -f "$AI4SE/repository/entries.yaml" ]]; then
  {
    echo "# Auto-detected build/test entry pointers (edit as needed)"
    echo "# W1: undetected systems must be explicit unknown — empty [] is not honest."
    if [[ -f "$ROOT/pom.xml" ]]; then
      echo "build:"
      echo "  - mvn -q -DskipTests package"
      echo "test:"
      echo "  - mvn -q test"
    elif [[ -f "$ROOT/package.json" ]]; then
      echo "build:"
      echo "  - npm run build"
      echo "test:"
      echo "  - npm test"
    elif [[ -f "$ROOT/build.gradle" || -f "$ROOT/build.gradle.kts" ]]; then
      echo "build:"
      echo "  - ./gradlew assemble"
      echo "test:"
      echo "  - ./gradlew test"
    else
      echo "build: unknown"
      echo "test: unknown"
    fi
  } > "$AI4SE/repository/entries.yaml"
fi

for f in rules/.gitkeep skills/.gitkeep knowledge/.gitkeep learning/.gitkeep; do
  mkdir -p "$(dirname "$AI4SE/$f")"
  touch "$AI4SE/$f"
done

if [[ ! -f "$STORY/README.md" ]]; then
  cat > "$STORY/README.md" <<'EOF'
# .story/

Per-story process artifacts live under `.story/<story-id>/`.
Managed by Delivery Orchestration; not business knowledge.
EOF
fi

echo "Done. Digitize further by editing .ai4se/repository/ (no AI analysis in this step)."
echo "Next: ensure baseline.md has no (fill); open a Story then build Analysis Context Package."
