package com.ai4se.review.tools;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;

/**
 * Generates a stable ReviewPackage under {@code review-package/generated/}.
 * No AI, no GitHub API — optional local {@code git} for changed-files.
 */
public final class ReviewPackageGenerator {

    public static final String SCHEMA_VERSION = "1.0";
    public static final String GENERATOR_NAME = "ai4se-review-tools";

    public static final List<String> REQUIRED_SECTIONS = Collections.unmodifiableList(Arrays.asList(
            "architecture",
            "changed-files",
            "tech-debt",
            "roadmap",
            "review-request"));

    private final Path repoRoot;

    public ReviewPackageGenerator(Path repoRoot) {
        if (repoRoot == null) {
            throw new IllegalArgumentException("repoRoot required");
        }
        this.repoRoot = repoRoot.toAbsolutePath().normalize();
    }

    public Path generate() throws IOException {
        return generate(newPackageId());
    }

    public Path generate(String packageId) throws IOException {
        if (packageId == null || packageId.trim().isEmpty()) {
            throw new IllegalArgumentException("packageId required");
        }
        Path templateDir = repoRoot.resolve("review-package").resolve("_template");
        Path outDir = repoRoot.resolve("review-package").resolve("generated").resolve(packageId);
        Files.createDirectories(outDir);

        for (String section : REQUIRED_SECTIONS) {
            String fileName = section + ".md";
            Path template = templateDir.resolve(fileName);
            Path target = outDir.resolve(fileName);
            if (Files.isRegularFile(template)) {
                Files.copy(template, target, StandardCopyOption.REPLACE_EXISTING);
            } else {
                writeUtf8(target, "# " + section + "\n\n> Placeholder — schema " + SCHEMA_VERSION + ".\n");
            }
        }

        fillChangedFiles(outDir.resolve("changed-files.md"));
        writeUtf8(outDir.resolve("manifest.json"), buildManifest(packageId));
        return outDir;
    }

    private void fillChangedFiles(Path changedFilesMd) throws IOException {
        List<String> files = listLocalGitChanges();
        StringBuilder body = new StringBuilder();
        body.append("# Changed Files\n\n");
        body.append("> Generated by ").append(GENERATOR_NAME)
                .append(" from local git (no GitHub API). Schema v")
                .append(SCHEMA_VERSION).append(".\n\n");
        body.append("## Files\n\n");
        if (files.isEmpty()) {
            body.append("_(none listed — working tree clean or git unavailable)_\n");
        } else {
            for (String file : files) {
                body.append("- `").append(file).append("`\n");
            }
        }
        writeUtf8(changedFilesMd, body.toString());
    }

    List<String> listLocalGitChanges() {
        List<String> files = new ArrayList<String>();
        try {
            addGitLines(files, "diff", "--name-only", "HEAD");
            addGitLines(files, "ls-files", "--others", "--exclude-standard");
        } catch (Exception ignored) {
            return Collections.emptyList();
        }
        // de-dup preserving order
        List<String> unique = new ArrayList<String>();
        for (String f : files) {
            if (!unique.contains(f)) {
                unique.add(f);
            }
        }
        return unique;
    }

    private void addGitLines(List<String> out, String... gitArgs) throws IOException, InterruptedException {
        List<String> cmd = new ArrayList<String>();
        cmd.add("git");
        cmd.addAll(Arrays.asList(gitArgs));
        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.directory(repoRoot.toFile());
        pb.redirectErrorStream(true);
        Process process = pb.start();
        BufferedReader reader = new BufferedReader(
                new InputStreamReader(process.getInputStream(), Charset.defaultCharset()));
        String line;
        while ((line = reader.readLine()) != null) {
            String trimmed = line.trim();
            if (!trimmed.isEmpty()) {
                out.add(trimmed);
            }
        }
        int code = process.waitFor();
        if (code != 0 && out.isEmpty()) {
            // ignore — leave empty list
        }
    }

    private String buildManifest(String packageId) {
        String generatedAt = isoUtcNow();
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"schemaVersion\": \"").append(SCHEMA_VERSION).append("\",\n");
        sb.append("  \"packageId\": \"").append(escapeJson(packageId)).append("\",\n");
        sb.append("  \"generatedAt\": \"").append(generatedAt).append("\",\n");
        sb.append("  \"generator\": \"").append(GENERATOR_NAME).append("\",\n");
        sb.append("  \"sections\": [\n");
        for (int i = 0; i < REQUIRED_SECTIONS.size(); i++) {
            sb.append("    \"").append(REQUIRED_SECTIONS.get(i)).append("\"");
            if (i + 1 < REQUIRED_SECTIONS.size()) {
                sb.append(",");
            }
            sb.append("\n");
        }
        sb.append("  ]\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String newPackageId() {
        SimpleDateFormat fmt = new SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US);
        fmt.setTimeZone(TimeZone.getTimeZone("UTC"));
        return "rp-" + fmt.format(new Date());
    }

    private static String isoUtcNow() {
        SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US);
        fmt.setTimeZone(TimeZone.getTimeZone("UTC"));
        return fmt.format(new Date());
    }

    private static String escapeJson(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static void writeUtf8(Path path, String content) throws IOException {
        Files.write(path, content.getBytes(Charset.forName("UTF-8")));
    }

    /** Resolve repo root: walk up from cwd looking for review-package/SCHEMA.md or pom.xml. */
    public static Path detectRepoRoot(Path start) {
        Path cur = start.toAbsolutePath().normalize();
        while (cur != null) {
            if (Files.isRegularFile(cur.resolve("review-package").resolve("SCHEMA.md"))
                    || Files.isRegularFile(cur.resolve("pom.xml"))) {
                return cur;
            }
            cur = cur.getParent();
        }
        return start.toAbsolutePath().normalize();
    }
}
